# Generated by Django 5.2.7 on 2025-11-02 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='comment_created_f25b05_idx',
            old_name='blog_commen_created_0e6ed4_idx',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
